config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  root 'breweries#index'

  resources :users
  resources :breweries
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :beer_clubs
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :memberships, only: [:new, :create]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
	include RatingAverage

	has_many :beers, dependent: :destroy
	has_many :ratings, through: :beers

  validates :name, presence: true
  validates :year, numericality: { less_than_or_equal_to: ->(_) { Time.now.year },
                                    only_integer: true }


  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  def self.top(n)
    Brewery.all.sort_by{ |b| -(b.average_rating || 0) }[0..n-1]
  end

	def print_report
    puts name
    puts "established at year #{year}"
    puts "number of beers #{beers.count}"
    puts "number of ratings #{ratings.count}"
  end

  def restart
    self.year = 2014
    puts "changed year to #{year}"
  end

  def to_s
    "#{name} since #{year}"
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_is_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]

  def skip_if_cached
    if params[:format] != 'json'
      @order = params[:order] || 'name'
      return render :index if fragment_exist? "brewerylist-#{@order}"
    end
  end

  # GET /breweries
  # GET /breweries.json
  def index
    case @order
      when 'year' then
        @active_breweries = Brewery.order(:year).active
        @retired_breweries = Brewery.order(:year).retired
      else
        @active_breweries = Brewery.order(:name).active
        @retired_breweries = Brewery.order(:name).retired
    end
  end

  def list
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  def toggle_activity
    ["name", "year"].each{ |f| expire_fragment("brewerylist-" + f) }
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice:"brewery activity status changed to #{new_status}"
  end  

  # POST /breweries
  # POST /breweries.json
  def create
    ["name", "year"].each{ |f| expire_fragment("brewerylist-" + f) }
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render action: 'show', status: :created, location: @brewery }
      else
        format.html { render action: 'new' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ["name", "year"].each{ |f| expire_fragment("brewerylist-" + f) }
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ["name", "year"].each{ |f| expire_fragment("brewerylist-" + f) }
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :year, :active)
    end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<div class="col-sm-4">
  <%= form_for(@brewery) do |f| %>
    <% if @brewery.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

        <ul>
        <% @brewery.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= f.label :name %><br>
      <%= f.text_field :name, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :year %><br>
      <%= f.number_field :year, class:"form-control" %>
    </div>
    <div class="form-group">
      <%= f.check_box :active %>
      <%= f.label :active, "the brewery is active" %>
    </div>  
    <div class="actions">
      <%= f.submit 'Save', class:"btn btn-primary" %>
      <%= link_to 'Cancel', breweries_path, class:'btn btn-warning' %>
    </div>
  <% end %>
</div>

app/views/breweries/_list.html.erb
<table class="table table-hover">
  <thead>
    <tr>
      <th> <%= link_to 'Name', breweries_path(order:"name") %> </th>
      <th> <%= link_to 'Year', breweries_path(order:"year") %> </th>
    </tr>
  </thead>

  <tbody>
    <% breweries.each do |brewery| %>
      <tr>
        <td><%= link_to brewery.name, brewery %></td>
        <td><%= brewery.year %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<% cache "brewerylist-#{@order}", skip_digest: true do %>
	<h2>Active</h2>
	<p> Number of active breweries: <%= @active_breweries.count %> </p>
	<%= render 'list', breweries: @active_breweries %>

	<h2>Retired</h2>
	<p> Number of retired breweries: <%= @retired_breweries.count %> </p>
	<%= render 'list', breweries: @retired_breweries %>
<% end %>

<br>
<%= link_to('New Brewery', new_brewery_path, class:'btn btn-primary') unless current_user.nil? %>

app/views/breweries/list.html.erb
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular.min.js"></script>
<script src="//ajax.googleapis.com/ajax/libs/angularjs/1.2.10/angular-resource.js"></script>

<script>
angular.module('BreweryApp', ['ngResource'])
  .controller('BreweriesController',
    ['$scope', '$resource', function($scope, $resource) {

  $scope.breweries = $resource('breweries.json').get();

  $scope.order = 'name';
}]);
</script>

<style type="text/css">
  th {
    padding: 0 10px;
  }
  th > span:hover {
    cursor: pointer;
    text-decoration: underline;
  }
</style>

<div ng-app="BreweryApp" ng-controller="BreweriesController">
  <br>
  <p>search:  <input ng-model="search" placeholder="name, year..."></p>

  <h2>Active Breweries</h2>
  <table class="table table-hover">
    <thead>
    <th><span ng-click="order='name'">name
      <i class="fa fa-sort-alpha-asc"></i><span></th>
    <th><span ng-click="order='year'">year
      <i class="fa fa-sort-numeric-asc"></i><span></th>
    <th><span ng-click="order='-count'">beers
      <i class="fa fa-sort-amount-desc"></i><span></th>
    </thead>
    <tr ng-repeat="b in breweries.active | orderBy:order | filter:search">
      <td>{{b.name}}</td>
      <td>{{b.year}}</td>
      <td>{{b.count}}</td>
    </tr>
  </table>
  <h2>Retired Breweries</h2>
  <table class="table table-hover">
    <thead>
    <th><span ng-click="order='name'">name
      <i class="fa fa-sort-alpha-asc"></i><span></th>
    <th><span ng-click="order='year'">year
      <i class="fa fa-sort-numeric-asc"></i><span></th>
    <th><span ng-click="order='-count'">beers
      <i class="fa fa-sort-amount-desc"></i><span></th>
    </thead>
    <tr ng-repeat="b in breweries.retired | orderBy:order | filter:search">
      <td>{{b.name}}</td>
      <td>{{b.year}}</td>
      <td>{{b.count}}</td>
    </tr>
  </table>  
</div>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

app/views/breweries/show.html.erb
<% cache @brewery do %>
  <h2><%= @brewery.name %>
    <% if not @brewery.active  %>
        <span class="label label-info">retired</span>
    <% end %>
  </h2>
  <p>
  	<em>Established at <%= @brewery.year %></em>
  </p>

  <h3>Beers</h3>
  <p>
   <% @brewery.beers.each do |beer| %>
     <%= link_to beer.name, beer %>
   <% end %>
  </p>

  <p>
    <strong>Rating:</strong>
    <% if @brewery.ratings.empty? %>
      No ratings yet!
    <% else %>
      Average of
      <%= pluralize @brewery.ratings.count, "rating" %>
      is <%= @brewery.average_rating %>
    <% end %>
  </p>
<% end %>

<br>
<%= link_to "Toggle Activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-warning" %>
<%= edit_and_destroy_buttons_for @brewery %>