config/routes.rb
Ratebeer::Application.routes.draw do
  resources :styles

  root 'breweries#index'

  resources :users
  resources :breweries
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :beers
  resources :beer_clubs
  resources :ratings, only: [:index, :new, :create, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
  resources :memberships, only: [:new, :create]

  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

  resources :places, only:[:index, :show]
  post 'places', to:'places#search'

  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'brewerylist', to:'breweries#list'

end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'Breweries', breweries_path %></li>
<li><%= link_to 'Beers', beers_path %></li>
<li><%= link_to 'Styles', styles_path %></li>
<li><%= link_to 'Ratings', ratings_path %></li>
<li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Clubs', beer_clubs_path %></li>
<li><%= link_to 'Search', '/places' %></li>
<% if current_user.nil? %>
	<li><%= link_to 'Signup', '/signup' %></li>
	<li><%= link_to 'Signin', '/signin' %></li>
<% else %>
	<li class="dropdown">
		<a href="#" class="dropdown-toggle" data-toggle="dropdown">
			<%= current_user.username %><b class="caret"></b>
		</a>
		<ul class="dropdown-menu">
			<li><%= link_to 'View Profile', user_path(current_user) %>
			<li><%= link_to 'Rate a Beer', new_rating_path %></li>
			<li><%= link_to 'Join a Club', new_membership_path %></li>
			<li><%= link_to 'Signout', '/signout', method: :delete %></li>
		</ul>
	</li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ratebeer" %></title>
    <link href="//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css" rel="stylesheet">
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Ratebeer" %>">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>

    <main role="main" class=".container">
      <%= render 'layouts/messages' %>

      <div class="row">
        <div class="col-md-8">
          <%= yield %>
        </div>
        <div class="col-md-4">
          <img src="http://static.squarespace.com/static/5005a359e4b0a8c4361f4b6a/t/527d05b5e4b00ec91674bda7/1392932267173/?format=200w" width="200">
          <p class="lead text-center">In beer we trust.</p>
        </div>
      </div>

    </main>
  </body>
</html>